### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by numinit** [numinit/porygon#5]
Creating a single TODO issue to track some stuff that's been on my list for a while. Some of these may spawn their own issues, some may not.

## Android

- [ ] finish/test Android/Android Wear BLE dumb client/server

- [ ] add Lua bindings to client/server for scriptability

## Lua API

- [ ] add color interpolation (study how the wristband works first)

## Wristband reversing

- [ ] actually successfully preorder the wristband (sort of important)

- [ ] firmware dump

**Comment by numinit** [comment]
If anyone ever figures out a place where the wristband won't be sold out, I'm all ears. ;)

**Comment by martijnthe** [comment]
> figure out how to dump the wristband firmware
Hint: the 16-bit service UUID 0xfef5 is owned by Dialog Semiconductor (see https://www.bluetooth.com/specifications/assigned-numbers/16-bit-uuids-for-members).

There are iOS and Android apps that talk to the service available here:
https://play.google.com/store/apps/details?id=com.dialog.suota&hl=en
https://itunes.apple.com/us/app/dialog-suota/id953141262?mt=8

I wonder if they just used the service as provided by this vendor.

**Comment by numinit** [comment]
Oh, excellent. I knew that UUID looked strange, but I never placed my finger on what it meant. Thanks for the heads-up.

**Comment by SpencerCarstens** [comment]
From what you have seen thus far, how likely do you feel that we would be able to interact with the app while spoofing the wristband ( laptop, other bluetooth device, etc. )?

If I find a band source I will shoot you an email.

**Comment by numinit** [comment]
>From what you have seen thus far, how likely do you feel that we would be able to interact with the app while spoofing the wristband ( laptop, other bluetooth device, etc. )?

Very likely, depends on the pairing process with the app. I've got stubs for emulated "hardware" in there right now.

**Comment by martijnthe** [comment]
`CERTIFICATE_SERVICE` sounds like there might be some sort of authentication going on?

**Comment by numinit** [comment]
That's what it seems like. `SFIDA_TO_CENTRAL` and `CENTRAL_TO_SFIDA` sound like they're used in pairing somehow.

**Comment by martijnthe** [comment]
Any idea whether public key crypto is used there? I can imagine they'd like to prevent counterfeit bands and would give each device a unique identity+certificate, so it's hard to counterfeit a device and to make it easy to block a stolen identity on their end. I guess you could mod the mobile app to bypass it though...

**Comment by numinit** [comment]
I'm going to take a guess that  they might be used to sign messages to ensure that the wristband is genuine, actually.

**Comment by numinit** [comment]
Wow, nice simulpost.

**Comment by numinit** [comment]
To your prior question, the code in there right now seems to not require any sort of authentication, and was likely used for lab devices. They probably will add authentication closer to the release of the wristband.

**Comment by numinit** [comment]
@SpencerCarstens

>If I find a band source I will shoot you an email.

Forgot to say, thanks for keeping an eye out :)

**Comment by kevincon** [comment]
Is there any new or useful info from [Applidium's article](https://applidium.com/en/news/unbundling_pokemon_go/) today (or [the accompanying GitHub repo](https://github.com/applidium/PokemonGo_Android_RE/tree/master/android/app/src/main/java/com/nianticproject/holoholo/sfida)) for the development of this project?

**Comment by numinit** [comment]
I gave that github repo a look the other day; it's virtually identical to what I have had locally.

There are some Unity services and RPC endpoints for the sfida interface I've been looking at as well that seem to support the findings above so far.

**Comment by numinit** [comment]
Also, there *are* authentication stubs in there already (with corresponding `onReceivedDummyCertificationChallenge` handlers for development devices):

```java
    public static byte[] getSecurityResponseForDebug() {
        return SfidaUtils.hexStringToByteArray("0400000000000000000000000000000000000000");
    }

    public static byte[] getSecurityResponseForDebug2() {
        return SfidaUtils.hexStringToByteArray("050000000000000000000000000000000000000000000000000000000000000000000000");
    }

    public static byte[] getSecurityResponseForDebug3() {
        return SfidaUtils.hexStringToByteArray("0300000001");
    }
```

**Comment by numinit** [comment]
Heard that the wristband's release got delayed to September:

http://www.androidauthority.com/pokemon-go-plus-delayed-706152/

**Comment by sabas1080** [comment]
Available version 0.37 support PGO+

We are creating a DIY version that apparently is recognized by the app
https://hackaday.io/project/12680-pokemon-go-plus-diy


Perhaps this can help

**Comment by numinit** [comment]
Nice. Yep, this will be on my plate again, if I can balance it with another semester of school.

**Comment by numinit** [comment]
(Hence why I've been rather silent on this recently)

**Comment by WIStudent** [comment]
Has anyone been able to establish a connection or pairing between a Pokemon Go Plus device and a device that is not a smartphone? I tried pairing the Plus device with a Raspberry Pi 3 but the Plus device always disconnects the connection immediately. 
Using `bluetoothctl`:
```
[bluetooth]# pair 7C:BB:8A:26:C7:D8
Attempting to pair with 7C:BB:8A:26:C7:D8
[CHG] Device 7C:BB:8A:26:C7:D8 Connected: yes
Failed to pair: org.bluez.Error.AuthenticationCanceled
[CHG] Device 7C:BB:8A:26:C7:D8 Connected: no
```
And the corresponding log using `btmon`:
```

< HCI Command: LE Set Scan Parameters (0x08|0x000b) plen 7      [hci0] 9.337313
        Type: Passive (0x00)
        Interval: 60.000 msec (0x0060)
        Window: 30.000 msec (0x0030)
        Own address type: Public (0x00)
        Filter policy: Ignore not in white list (0x01)
> HCI Event: Command Complete (0x0e) plen 4                     [hci0] 9.337807
      LE Set Scan Parameters (0x08|0x000b) ncmd 1
        Status: Success (0x00)
< HCI Command: LE Set Scan Enable (0x08|0x000c) plen 2          [hci0] 9.337856
        Scanning: Enabled (0x01)
        Filter duplicates: Enabled (0x01)
> HCI Event: Command Complete (0x0e) plen 4                     [hci0] 9.338300
      LE Set Scan Enable (0x08|0x000c) ncmd 1
        Status: Success (0x00)
> HCI Event: LE Meta Event (0x3e) plen 39                      [hci0] 10.236089
      LE Advertising Report (0x02)
        Num reports: 1
        Event type: Connectable undirected - ADV_IND (0x00)
        Address type: Public (0x00)
        Address: 7C:BB:8A:26:C7:D8 (OUI 7C-BB-8A)
        Data length: 27
        Flags: 0x06
          LE General Discoverable Mode
          BR/EDR Not Supported
        Name (complete): Pokemon GO Plus
        Unknown EIR field 0x20: 6204c52100
        RSSI: -69 dBm (0xbb)
< HCI Command: LE Set Scan Enable (0x08|0x000c) plen 2         [hci0] 10.236169
        Scanning: Disabled (0x00)
        Filter duplicates: Disabled (0x00)
> HCI Event: Command Complete (0x0e) plen 4                    [hci0] 10.238023
      LE Set Scan Enable (0x08|0x000c) ncmd 1
        Status: Success (0x00)
< HCI Command: LE Create Connection (0x08|0x000d) plen 25      [hci0] 10.238076
        Scan interval: 60.000 msec (0x0060)
        Scan window: 60.000 msec (0x0060)
        Filter policy: White list is not used (0x00)
        Peer address type: Public (0x00)
        Peer address: 7C:BB:8A:26:C7:D8 (OUI 7C-BB-8A)
        Own address type: Public (0x00)
        Min connection interval: 50.00 msec (0x0028)
        Max connection interval: 70.00 msec (0x0038)
        Connection latency: 0x0000
        Supervision timeout: 420 msec (0x002a)
        Min connection length: 0.000 msec (0x0000)
        Max connection length: 0.000 msec (0x0000)
> HCI Event: Command Status (0x0f) plen 4                      [hci0] 10.238879
      LE Create Connection (0x08|0x000d) ncmd 1
        Status: Success (0x00)
> HCI Event: LE Meta Event (0x3e) plen 19                      [hci0] 10.370076
      LE Connection Complete (0x01)
        Status: Success (0x00)
        Handle: 64
        Role: Master (0x00)
        Peer address type: Public (0x00)
        Peer address: 7C:BB:8A:26:C7:D8 (OUI 7C-BB-8A)
        Connection interval: 67.50 msec (0x0036)
        Connection latency: 0.00 msec (0x0000)
        Supervision timeout: 420 msec (0x002a)
        Master clock accuracy: 0x00
< HCI Command: LE Read Remote Used Fea.. (0x08|0x0016) plen 2  [hci0] 10.370407
        Handle: 64
@ Device Connected: 7C:BB:8A:26:C7:D8 (1) flags 0x0000
        02 01 06 10 09 50 6f 6b 65 6d 6f 6e 20 47 4f 20  .....Pokemon GO
        50 6c 75 73 06 20 62 04 c5 21 00                 Plus. b..!.
> HCI Event: Command Status (0x0f) plen 4                      [hci0] 10.375334
      LE Read Remote Used Features (0x08|0x0016) ncmd 1
        Status: Success (0x00)
> HCI Event: LE Meta Event (0x3e) plen 12                      [hci0] 10.762467
      LE Read Remote Used Features (0x04)
        Status: Remote User Terminated Connection (0x13)
        Handle: 64
        Features: 0x1f 0x00 0x00 0x00 0x00 0x00 0x00 0x00
          LE Encryption
          Connection Parameter Request Procedure
          Extended Reject Indication
          Slave-initiated Features Exchange
          LE Ping
> HCI Event: Disconnect Complete (0x05) plen 4                 [hci0] 10.763149
        Status: Success (0x00)
        Handle: 64
        Reason: Remote User Terminated Connection (0x13)
@ Device Disconnected: 7C:BB:8A:26:C7:D8 (1) reason 3
```

Trying to pair the Plus device with a Windows machine also didn't work. I guess it is checking what kind of device is initiating the connection/pairing and disconnects as soon as it suspects that it is not a smartphone.

**Comment by Landrash** [comment]
@WIStudent Have a look at the [btproxy](https://github.com/conorpp/btproxy). Might be of help to you.

**Comment by sabas1080** [comment]
or [Bltejuice](https://github.com/DigitalSecurity/btlejuice) @WIStudent

**Comment by bettse** [comment]
>Has anyone been able to establish a connection or pairing between a Pokemon Go Plus device and a device that is not a smartphone? 

I've been playing with seeing if I could connect to the PGo+ using my desktop (macOS).  So far, I’ve found that trying to read or enable notify for most characteristics of the ‘device’ service will return an error.  The path I’ve been most successful with is using the certification service.  I’m able to enable notify for the characteristic that has the notify property (its called the “commands” characteristic in the android source), and to read the value of the characteristic with the read property (‘sfida_to_central’).

The commands characteristic notifies with a value of 4 bytes, all 0’s.  The sfida_to_central returns a 378 bytes value that starts with 4 0’s, then continues on with data that doesn’t have a pattern I see.

I did find that I can repeatedly read the sfida_to_central, even without first subscribing to ‘commands’, and get the same value back multiple times.  It seems that the subscription to ‘commands’ is what causes the sfida_to_central value to change, but it appears more significant than simply incrementing or similar.

Based on https://blog.fortinet.com/2016/08/11/pokemon-go-plus-preview-through-reverse-engineering  I believe that it may be a nonce, or some encrypted value, used to validate the device is authentic. 

After about 30 seconds, the device disconnects, regardless of how many times i've tried to read the sfida_to_central value.  If I write to the central_to_sfida characteristic, there is no bluetooth error, but the device blinks red and vibrates, in what appears to be an error sequence.

**Comment by WIStudent** [comment]
I finally solved my issue. I didn't consider that I needed to initiate an unpairing procedure at the Pokemon Go Plus device itself before I can pair it with another device. The Plus device memorizes the last device it was paired with and rejects any connection/pairing request that comes from a different device. The unpairing procedure is described in the manual.

**Comment by WIStudent** [comment]
I have some bad news. Not only does the Pokemon Go app check if it is talking to a genuine Pokemon Go Plus (PGP) peripheral, but the PGP peripheral is also checking if it is talking to a genuine Pokemon Go app. After many failed attempts I was able to capture the connection initialization between a PGP peripheral and the Pokemon Go app using the Bluefruit LE Sniffer from Adafruit. Here is what I observed:

**Characteristic UUIDs:**
- sfida_commands: bbe87709-5b89-4433-ab7f-8b8eef0d8e39
- sfida_to_central: bbe87709-5b89-4433-ab7f-8b8eef0d8e3a
- central_to_sfida: bbe87709-5b89-4433-ab7f-8b8eef0d8e38
- button: 21c50462-67cb-63a3-5c4c-82b5b9939aed
- battery level: 00002a19-0000-1000-8000-00805f9b34fb

**Steps:**
1. App subscribes to sfida_commands notification
2. PGP sends notification (4 Bytes): [0x00, 0x00, 0x00, 0x00]
3. App reads from sfida_to_central (378 Bytes), first 4 bytes are [0x00, 0x00, 0x00, 0x00]
4. App writes to central_to_sfida (20 Bytes), first 4 bytes are [0x01, 0x00, 0x00, 0x00]
5. PGP sends notification (4 Bytes): [0x01, 0x00, 0x00, 0x00]
6. App reads from sfida_to_central (52 Bytes): first 4 bytes are [0x01, 0x00, 0x00, 0x00]
7. App writes to central_to_sfida (52 Bytes): first 4 bytes are [0x02, 0x00, 0x00, 0x00]
8. PGP sends notification (4 Bytes): [0x02, 0x00, 0x00, 0x00]
9. App reads from sfida_to_central (20 Bytes): first 4 bytes are [0x02, 0x00, 0x00, 0x00]
10. App writes to central_to_sfida (20 Bytes): first 4 bytes are [0x00, 0x00, 0x00, 0x00]
11. PGP sends notification (4 Bytes): [0x04, 0x00, 0x23, 0x00]
12. App subscribes to notifications on button
13. App reads battery level two times

Trying to connect to the PGP peripheral with an application that is not the Pokemon Go app fails in step 4. Both writing the intercepted message and writing [0x01, 0x00, 0x00, 0x00] + 16 random bytes to the central_to_sfida characteristic results in a notification with the value [0x04, 0x00, 0x21, 0x00] on the sfida_commands characteristic and the termination of the connection.

I don't think that it will be possible to use the PGP peripheral with other applications without knowing the full meaning of the exchanged messages. Figuring that out will most likely require taking a close look at the Pokemon Go app itself.

**Comment by numinit** [comment]
@WIStudent I've been looking at the handshake protocol; the primary crypto used appears to be AES operating in CTR mode, with a key established on initial connection. Swore I'd look at it the other day, but didn't get around to it.

**Comment by numinit** [comment]
@WIStudent

Pairing:

```
RX: NOTIFY 00000000
RX: 00000000 <blob data: 112 bytes / 262 bytes>
TX: 01000000 <16 bytes>

RX: NOTIFY 01000000
RX: 01000000 <16 bytes> <32 bytes>
TX: 02000000 <16 bytes> <32 bytes>

RX: NOTIFY 02000000
RX: 02000000 <16 bytes>
TX: 00000000 <16 bytes> <32 bytes>

RX: NOTIFY 04002300
TX: 0240003b <60 bytes>
```

Certification:
```
RX: NOTIFY 03000000
RX: 03000000 <32 bytes>
TX: 04000000 <16 bytes>

RX: NOTIFY 04000100
TX: 05000000 <32 bytes>

RX: NOTIFY 05000000
RX: 05000000 <16 bytes>
TX: 03000000 01

RX: NOTIFY 04000200
[pgo+ is now functional]
```
